[project]
name = "crud-alchemy"
version = "0.0.0"
dependencies = [
]

[tool.setuptools]
package-dir = {"" = "src"}

[build-system]
requires = ["setuptools"]

[project.optional-dependencies]
dev = [
    "pytest>=7.2.1,<8.0",
    "mock>=5.0.1,<6.0",
    "flake8>=6.0,<7.0",
]

gbol = [
    "lgbt",
]
